### ISSUE TITLE
MinecraftDev adds @Shadow to fields when pasting code from other classes even when it's not mixin

### ISSUE THREAD

**Issue by Barteks2x** [minecraft-dev/MinecraftDev#148] opened 2017-02-01 15:58 UTC

**Comment by Minecrell** [comment] 2017-02-05 13:26
I cannot reproduce this. Additionally I have no idea why this would happen since I check if you are pasting to a Mixin class: https://github.com/minecraft-dev/MinecraftDev/blob/2016.3/src/main/kotlin/com/demonwav/mcdev/platform/mixin/editor/MixinCopyPasteReferenceProcessor.kt#L65-L73

**Comment by Barteks2x** [comment] 2017-02-05 13:55
It might be related to the bug where it didn't detect my mixins as mixins when I had `build.gradle.kts`, but no idea how that could be related. I will try to come up with exact steps to reproduce it with the current version.

**Comment by Barteks2x** [comment] 2017-02-08 12:26
With the following source class:
```java
public class Test {
    /// start here
    protected static int field = 0;

    public int getField() {
        return field;
    }
    // end here
}
```
Copying the whole content of the class (marked with comments) and pasting it into another class, IDEA will ask me if I want to import the field twice, clicking yes the fiest time will add import, clicking yes thesecond time will add `@org.spongepowered.asm.mixin.Shadow` to the field. So it was probably my fault for telling it to import the field, but adding shadow to non-mixin classes is still wrong.

**Comment by Minecrell** [comment] 2017-02-08 20:11
Fixed in https://github.com/minecraft-dev/MinecraftDev/commit/5db9fa9d508df245e70ad66039097d3a91ae7689

**Closed by Minecrell** 2017-02-08 20:11 UTC
Labels: platform: mixins, status: accepted, type: bug
