### ISSUE TITLE
Support 1.7.10

### ISSUE THREAD

**Issue by hohserg** [minecraft-dev/MinecraftDev#312] opened 2017-10-11 15:01 UTC
Why in the choice of versions there is no 1.7.10?
screenshot:
https://image.prntscr.com/image/_1Bt2dBKSZOyAVmjdx8Hmw.png

**Comment by loordgek** [comment] 2017-10-11 15:05
because it is old and needs to die

**Comment by hohserg** [comment] 2017-10-11 15:17
This is not an argument. I still have a server 1.7.10.
Support 1.7.10 is no very different from the newer versions. Why is it artificially removed? Can you specify the location in the code where this happens? I could build a plugin for myself with support 1.7.10.

**Comment by Mumfrey** [comment] 2017-10-11 15:18
It's not "artificially removed", the toolchain for such an ancient version is so different from the newer toolchain that it would be tantamount to supporting an entirely different game.

> Support 1.7.10 is no very different from the newer versions

Wrong.

> I could build a plugin for myself with support 1.7.10.

Lol good luck.

**Comment by Minecrell** [comment] 2017-10-11 15:24
Duplicate of #76, #165, #190, #295 and #296.

Note that just because you have MinecraftDev installed doesn't mean that you cannot work on projects that are built for 1.7.10. You just need to setup the project manually and some code assistance features might be fully working.

**Closed by Minecrell** 2017-10-11 15:24 UTC
Labels: type: duplicate

**Comment by hohserg** [comment] 2017-10-11 15:26
Ok. Perhaps I did not fully appreciate the functionality of the plug-in, because I stopped at the fact that I can not create a project for the version I need. I'll see what adds the plug-in to the ide on the examples of newer versions. However, the assembly workspace is not much different:
gradlew setupDecomWorkspace
gradlew gIR

**Comment by DemonWav** [comment] 2017-10-11 22:51
> This is not an argument.
I'll be the one who decides that.
> I still have a server 1.7.10
I don't care.
> However, the assembly workspace is not much different:
> gradlew setupDecomWorkspace
We're not referring to the frontend, the fact that the command is the same is irrelevant.
