### ISSUE TITLE
Projects created using SBT are not recognized as Sponge plugins

### ISSUE THREAD

**Issue by Katrix-** [minecraft-dev/MinecraftDev#44] opened 2016-08-07 16:46 UTC
As said, if a project is created using SBT, it isn't recognized. Only tested with Sponge. Don't know how it is for others.

**Comment by gabizou** [comment] 2016-08-08 14:55
Is it possible for you to use `sbt` with ForgeGradle?

**Comment by Katrix-** [comment] 2016-08-08 15:20
Don't think so, so it shouldn't be a problem for Forge at least

**Comment by DemonWav** [comment] 2016-08-08 15:30
Yep, looks like even when doing Scala work with Forge you still use Gradle. http://www.minecraftforge.net/wiki/Scala

**Comment by DemonWav** [comment] 2016-08-09 16:14
Right now I think I'm going to file this under if people really want this added, it can be PR'ed, or some of the grunt work can be done beforehand for us. We were never intending to support SBT, but I have no issues supporting it, I'm just not sure I want to put the effort into adding support for it currently. If someone wanted to add in the SBT build system to the plugin I would be more than happy to merge that PR.

This plugin uses a BuildSystem API that I built, which is implemented by the `MavenBuildSystem` and `GradleBuildSystem` classes. I feel like these are decent enough examples to look at how to add a new build system to the plugin, if someone wanted to give it a shot. I can always answer any questions that may arise, though.

**Comment by DemonWav** [comment] 2017-03-05 07:54
Due to that commit, once [feature/facets](https://github.com/minecraft-dev/MinecraftDev/tree/feature/facets) is merged SBT will be fully supported. Not actually something that was intended with that feature branch, but a happy by-product of it. @Katrix-

**Comment by DemonWav** [comment] 2017-03-08 19:58
Fixed in #170.

**Closed by DemonWav** 2017-03-08 19:58 UTC
Labels: status: accepted, type: enhancement
